name: Django CI

on: [push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 .
        working-directory: ./HMS

      - name: Run black
        run: |
          black . check
        working-directory: ./HMS

      - name: Set to pass with failures
        if: always()
        run: echo "This job will pass with failures"
